# Pipeline that builds and pushes the microsoft/mlopspython image.
resources:
- repo: self

pool: 
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - master

  paths:
    include:
    - environment_setup/Dockerfile
    - environment_setup/docker-image-pipeline.yml

variables:
  containerRegistry: $[coalesce(variables['acrServiceConnection'], 'acrconnection')]
  imageName: $[coalesce(variables['agentImageName'], 'mlops/oilwells')]
  amlsdkversion: 1.6.0
  githubrelease: 3.0.0
        
steps:
  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageName)'
      tags: |
       ${{format('build-{0}', '$(Build.BuildNumber)')}}
       ${{format('amlsdk-{0}', '$(amlsdkversion)')}}
       ${{format('release-{0}', '$(githubrelease)')}}
       latest
      buildContext: '$(Build.SourcesDirectory)' 
      dockerFile: '$(Build.SourcesDirectory)/environment_setup/Dockerfile'
